name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Hello! Thank you for posting this issue. It means alot to me getting feedback so I can fix it.'
        pr-message: 'Hi! Thank you for that. I will look at it.'
